#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: v1
data:
    tls.crt: #@ base64.encode(data.values.tlsCertificate)
    tls.key: #@ base64.encode(data.values.tlsPrivateKey) 
kind: Secret
metadata:
    name: #@ data.values.harborSecretName
    namespace:  #@ data.values.harborNamespace
type: kubernetes.io/tls